version: '3'
services:
  lb:
    image: dockercloud/haproxy:1.6.7
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443

  app:
    image: createkio/flight_plan:latest
    command: sleep 100d
    volumes:
      - .:/flight_plan
    depends_on:
      - db
      - selenium
    expose:
      - 3000
    environment:
      - SELENIUM_REMOTE_HOST=selenium
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD
  db:
    image: mysql:5.7.19
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  selenium:
    image: selenium/standalone-chrome-debug:3.5.2
    ports:
      - 4444:4444

