version: '3'
services:
  lb:
    image: dockercloud/haproxy:1.6.7
    links:
      - app
      - webpack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443

  app:
    image: createkio/flight_plan:latest
    command: sh -c '
      rm -f /flight_plan/tmp/pids/server.pid &&
      bundle &&
      if [ "$BYEBUG" -eq "1" ]; then sleep 100d; else rails s; fi
      '
    volumes:
      - .:/flight_plan
    depends_on:
      - db
      - redis
    expose:
      - 3000
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD
      - VIRTUAL_HOST=dev.createk.io
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - WEBPACKER_DEV_SERVER_PORT=80
    env_file:
      - .env
  db:
    image: mysql:5.7.19
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  webpack:
    image: createkio/flight_plan:latest
    command: >
      sh -c '
        yarn install --ignore-engines &&

        if [ "$DEBUGGER" -eq "1" ]; then
          sleep 100d;
        else
          ./bin/webpack-dev-server
        fi
      '
    volumes:
      - .:/flight_plan
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=webpack.dev.createk.io


  redis:
    image: redis:3.2

  sidekiq:
    image: createkio/flight_plan:latest
    command: sh -c 'bundle && bundle exec sidekiq'
    volumes:
      - .:/flight_plan
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD
    env_file:
      - .env
