version: '3'
services:
  lb:
    image: traefik:2.3.6
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tools/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./tools/traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./tools/ssl_certs:/ssl_certs

  app:
    image: createkio/flight_plan:latest
    command: sh -c '
      rm -f /flight_plan/tmp/pids/server.pid &&
      bundle &&
      if [ "$BYEBUG" -eq "1" ]; then sleep 100d; else bin/rails s; fi
      '
    volumes:
      - .:/flight_plan
      - gems:/usr/local/bundle
      - node_modules:/flight_plan/node_modules
    depends_on:
      - db
      - redis
    expose:
      - 3000
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - WEBPACKER_DEV_SERVER_HOST=webpack
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`dev.createk.io`)
      - traefik.http.routers.app.tls=true
    env_file:
      - .env

  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  webpack:
    image: createkio/flight_plan:latest
    command: >
      sh -c '
        yarn install --ignore-engines &&

        if [ "$DEBUGGER" -eq "1" ]; then
          sleep 100d;
        else
          ./bin/webpack-dev-server
        fi
      '
    volumes:
      - .:/flight_plan
      - gems:/usr/local/bundle
      - node_modules:/flight_plan/node_modules
    expose:
      - 443
    labels:
      - traefik.enable=true
      - "traefik.http.routers.webpack.rule=Host(`webpack.dev.createk.io`) || (Host(`dev.createk.io`) && PathPrefix(`/sockjs-node/`))"
      - traefik.http.routers.webpack.tls=true

  redis:
    image: redis:3.2

  sidekiq:
    image: createkio/flight_plan:latest
    command: sh -c 'bundle exec sidekiq'
    volumes:
      - .:/flight_plan
      - gems:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    env_file:
      - .env

volumes:
  postgresql_data:
  gems:
  node_modules:
