---
version: 2
jobs:
  build:
    docker:
      - image: createkio/flight_plan:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
        environment:
          DB_HOST: 127.0.0.1
          DB_USERNAME: postgres
          DB_PASSWORD: password
          RAILS_ENV: test
      - image: postgres:12.2-alpine
        environment:
          POSTGRES_PASSWORD: password
      - image: redis:3.2

    working_directory: ~/repo

    parallelism: 2
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: |
            bundle install \
            --jobs "$(getconf _NPROCESSORS_ONLN)" \
            --retry 2 \
            --without development
      - run:
          name: Yarn Install
          command: yarn install --ignore-engines || true
      - run:
          name: Database setup
          command: >
            retries=5

            until nc -z $DB_HOST:5432; do
              retries="$(("$retries" - 1))"

              if [ "$retries" -eq 0 ]; then
                echo "Failed to reach PostgreSQL" >&2
                exit 1
              fi

              sleep 5
              echo "Waiting for PostgreSQL ($retries retries left)"
            done

            rake db:reset
      - run:
          name: Run Specs
          environment:
            DISABLE_SPRING: 1
          command: >
            circleci tests glob "spec/**/*_spec.rb" | circleci tests split | \
              tee /dev/stderr | xargs bin/rspec \
              --require rspec_junit_formatter \
              --format RspecJunitFormatter --out tmp/test-results/rspec/results.xml \
              --format documentation
      - store_artifacts:
          path: log
          destination: log
      - store_artifacts:
          path: tmp/capybara
          destination: capybara
      - store_artifacts:
          path: tmp/rspec
          destination: rspec
      - store_test_results:
          path: tmp/test-results
      - add_ssh_keys:
          fingerprints:
            - 'ab:68:2e:b6:40:01:25:79:e0:70:ba:95:ef:f7:98:85'
      - deploy:
          name: Deploy to Heroku (master only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                sh .circleci/setup_heroku.sh

                git push --force git@heroku.com:flight-plan-createk.git HEAD:refs/heads/master
            fi

