# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    workDir: /flight_plan

    docker:
      - image: createkio/flight_plan:latest
        environemt:
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: mysecretpassword
          RAILS_ENV: test
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysecretpassword

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: database setup
          command: |
            until curl -s -o /dev/null $DB_HOST:3306; do
              sleep 5;
              echo "Waiting for MySQL";
            done;
            rake db:reset

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
