---
version: 2.1

orbs:
  docker: circleci/docker@1.5.0

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: createkio/flight_plan
          tag: 'next,ruby26'
