---

version: 2
jobs:
  build:
    docker:
      - image: createkio/flight_plan:latest
        environment:
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: mysecretpassword
          RAILS_ENV: test
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysecretpassword

    working_directory: ~/repo

    parallelism: 2
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: |
            bundle install \
            --jobs 20 \
            --retry 2 \
            --without development
      - run:
          name: Yarn
          command: yarn install
      - run:
          name: Database setup
          command: |
            until curl -s -o /dev/null $DB_HOST:3306; do
              sleep 5;
              echo "Waiting for MySQL";
            done;
            rake db:reset
      - run:
          name: Run Specs
          environment:
            DISABLE_SPRING: 1
          command: >
            circleci tests glob "spec/**/*_spec.rb" | circleci tests split | \
              xargs bin/rspec 
      - store_artifacts:
          path: tmp/capybara
          destination: capybara

    deployment:
      production:
        branch: master
        commands:
          - git push git@heroku.com:flight-plan-createk.git $CIRCLE_SHA1:master
          - heroku run rake db:migrate --app flight-plan-createk

