steps:
  - label: ':rspec:'
    key: spec
    plugins:
      - docker-login#v2.1.0:
          username: createkci
          password-env: DOCKER_LOGIN_PASSWORD
      - docker-compose#v3.9.0:
          run: app
          env:
            - RAILS_ENV=test
            - DISABLE_SPRING=1
            - FERRUM_DEFAULT_TIMEOUT=10
            - FERRUM_PROCESS_TIMEOUT=20
            # used for names of JUnit XML files
            - BUILDKITE_JOB_ID
            # Used to choose which spec files to run
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_PARALLEL_JOB
            - BUILDKITE_PARALLEL_JOB_COUNT
    parallelism: 2
    timeout_in_minutes: 5
    commands:
      - .buildkite/test.sh
    env:
      BYEBUG: '0'
      DEBUGGER: '0'
    artifact_paths:
      - log/*.log
      - tmp/rspec-junit-*.xml
      - tmp/rspec/*.txt
      - tmp/capybara/*
      - tmp/screenshots/*

  - wait: ~
    continue_on_failure: true

  - label: ':junit:'
    plugins:
      - junit-annotate#v1.9.0:
          artifacts: tmp/rspec-junit-*.xml
          job-uuid-file-pattern: rspec-junit-([^.]+)\.xml
          failure-format: file
