default: &default
  adapter: redis
  url: <%= ENV[ENV['REDIS_PROVIDER'].presence || 'REDIS_URL'] %>
  channel_prefix: 'flight_plan_<%= Rails.env %>'

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
