---
features:
  - name: harvest_button
    description: >
      Show a "Track time with Harvest" button on the ticket modal
    default: on

  - name: kpis
    description: >
      Enable the KPIs dashboard at /boards/:id/kpis
    default: on

  - name: normalised_responses
    description: >
      Use ReduxLoader to generate JSON in normalised form

  - name: realtime_updates
    description: >
      Send updates to board over WebSockets
    default: on

  - name: self_serve_features
    description: >
      Allow users to enable certain features for themselves

  - name: broadcasts
    description: >
      Broadcast model changes over WebSockets using after_commit hooks
